.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2022 Marselo <falso.endereco@gmail.com>
.\"
.TH PKM85 1 
.SH NAME
pkm85 - git log util
.SH SYNOPSIS
pkm85 [OPTION]
.SH DESCRIPTION
pkm85 é um script simples que executa o comando 
.B git log
para buscar arquivos criados e modificados por autor e período informado. O resultado é gravado em três
arquivos, conforme abaixo. 
.TP
all
Lista todos os arquivos criados/modificados agrupados por commit
.TP  
no-dups
O mesmo conteúdo do arquivo  
.B all, 
porém em caso de arquivo modificado mais de uma vez no período, lista apenas o commit mais recente
.TP   
dups
Lista os arquivos/commits excluídos do arquivo 
.B no-dups
.SS NOTES 
.TP
1-
Se um arquivo foi criado e modificado no período, tanto a criação quanto a modificação mais recente são listados no 
.B no-dups
.TP
2- 
Commits de
.B merge
não são listados em nenhum dos arquivos

.SS GIT LOG COMMAND
 
O comando completo executado pelo script é:

git log --author=<author> --since=<since - 1 day> --until=<until> --name-status 
.B --no-merges
--pretty="format:%h %ad %s" --date=format:"%F %H:%M" 
.SH OPTIONS 
.TP  
-g, --gui 
executa em modo gui (default)
.TP  
-t, --terminal 
executa em modo terminal
.TP  
-h, --help 
exibe esta ajuda e encerra
.TP  
-v, --version
exibe número da versão
.SH SEE ALSO
Manual 
.B git log
https://git-scm.com/docs/git-log/pt_BR
.SH AUTHORS
The
.B pkm85 
script was written by 
Marselo Maciel <falso.endereco@gmail.com>
